# Jordi Casas - 11/07/2025
# Task to verify if a folder exists
# Expected variables: expected_folder: path to the folder to check
# Expected permissions: expected_permissions: In format '0755'
# Output registered: folder_permissions_folder_name


- name: Obtenir informació del directori {{ expected_folder }}
  ansible.builtin.stat:
    path: "{{ expected_folder }}"
  register: folder

- name: Definir variables booleanes per a l'existència
  ansible.builtin.set_fact:
    # Verifica si el directori existeix
    folder_permissions{{ expected_folder | regex_replace('/', '_') | trim | lower }}: "{{ folder.stat.mode == expected_permissions if folder.stat.exists else false }}"
