# Jordi Casas - 10/04/2025
# Playbook que comprova si existeix un usuari en un sistema
- name: Comprovar si un usuari existeix
  # A quins hosts aplica
  hosts: servers
  # Fitxer de variables que utilitza
  vars_files: servers.yml

  tasks:
  # Obtenir els usuaris
  - name: Obtenir tots els usuaris
    ansible.builtin.getent:
      database: passwd
      split: ':'

  # Buscar si existeix l'usuari i reportar un missatge per consola
  - name: Comprovar si un usuari existeix
    ansible.builtin.debug:
      msg: L'usuari existeix
    # "usuari" és la variable definida a vars.yml
    when: ( usuari in getent_passwd.keys() )
