# Jordi Casas - 10/04/2025
# Playbook que crea un usuari i l'afegeix al grup de sudo
- name: Crear un usuari
  # A quins hosts aplica
  hosts: servers
  # Requereix privilegis d'administrador
  become: true
  # Fitxer de variables que utilitza
  vars_files: vars.yml

  # Definició de les tasques a executar
  tasks:

  # Crear l'usuari
  - name: Crear un usuari
    user:
      name: "{{ usuari }}"
      password: "{{ password | password_hash('sha512') }}"
      shell: /bin/bash
      state: present

  # Determinar quin és el grup de sudo del sistema
  - name: Buscar si el sistema utilitza el grup wheel
    command:
      cmd: "grep 'wheel' /etc/group"
    register: result
    failed_when: result.rc != 0 and result.rc != 1
    check_mode: false
    changed_when: false

  # Depenent de si utilitza wheel o sudo afegir-lo segons pertoqui
  - name: Si ha trobat el grup wheel, afegir-lo al grup
    user:
      name: "{{ usuari }}"
      groups: wheel
      append: yes
    when: result.rc == 0

  - name: Sino afegir-lo al grup de sudo
    user:
      name: "{{ usuari }}"
      groups: sudo
      append: yes
    when: result.rc != 0
