# Jordi Casas - 10/04/2025
# Playbook que crea un usuari i l'afegeix al grup de sudo corresponent en funció del sistema
- name: Crear un usuari
  # A quins hosts aplica
  hosts: servers
  # Requereix privilegis d'administrador
  become: true
  # Fitxer de variables que utilitza
  vars_files: servers.yml
  # Definir una variable en funció de la distribució de Linux que indiqui el grup de sudo
  vars:
    sudoGroup: "{{ 'sudo' if ansible_facts['os_family'] == 'Debian' else 'wheel' }}"

  # Definició de les tasques a executar
  tasks:

  # Crear l'usuari - usuari i password són variables definides en vars.yml
  - name: Crear un usuari
    user:
      name: "{{ usuari }}"
      password: "{{ password | password_hash('sha512') }}"
      shell: /bin/bash
      state: present

  - name: Afegir l'usuari al grup segons el sistema
    user:
      name: "{{ usuari }}"
      groups: "{{ sudoGroup }}"
      append: yes
