# Jordi Casas - 30/06/2025
# Playbook que crea distribueix una clau d'un usuari als sistemes
- name: Crear un usuari
  # A quins hosts aplica
  hosts: servers
  # Requereix privilegis d'administrador
  become: true
  # Fitxer de variables que utilitza
  vars_files: servers.yml

  # Definició de les tasques a executar
  tasks:

  # Afegir una clau pública a un usuari
  - name: Copiar la clau pública
    ansible.posix.authorized_key:
      user: "{{ usuari }}"
      state: present
      key: "{{ clau_usuari_prova }}"

  - name: Canviar l'usuari perquè no requereixi password per fer sudo en màquines Ubuntu
    lineinfile:
      path: /etc/sudoers.d/usr_prova-user
      create: true
      state: present
      line: '"{{ usuari }}" ALL=(ALL) NOPASSWD:ALL'
      insertafter: EOF
    when: ansible_facts['os_family'] == "Debian"

  - name: Canviar l'usuari perquè no requereixi password per fer sudo en màquines Alpine
    lineinfile:
      path: /etc/doas.d/usr_prova.conf
      create: true
      state: present
      line: 'permit nopass :{{ usuari }}'
      insertafter: EOF
    when: ansible_facts['os_family'] == "Alpine"
