# Jordi Casas - 14/04/2025
# Playbook que instal.la paquets necessaris. Té en compte la versió del sistema instal.lat.
- name: Instal.lar paquets
  # A quins hosts aplica
  hosts: servers
  # Requereix privilegis d'administrador
  become: true
  # Fitxer de variables que utilitza
  vars_files: vars.yml

  # Definició de les tasques a executar
  tasks:

  # Instal.lar amb el gestor de paquets adient segons el sistema
  - name: Si es alpine instal.lar el bash
    community.general.apk:
      name: bash
      update_cache: true
    when: ansible_facts['os_family'] == "Alpine"
