# Jordi Casas - 10/04/2025
# Playbook que instal.la Docker a tots els servidors
# Invoca el rol creat amb les tasques d'instal.lació
---
- name: Instal·lar Docker en tots els servidors
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - instalar_docker
