# Jordi Casas - 24/06/2025
# Playbook que instal.la Nginx als servidors web
# Invoca el rol creat amb les tasques d'instal.lació
---
- name: Desplegar Frontal Web (Nginx)
  hosts: webservers
  become: yes
  gather_facts: yes # Necessari per a les variables com ansible_hostname
  roles:
    - nginx_web
  vars:
    db_server_ip: "{{ hostvars['bbdd_srv1']['ansible_host'] }}" # Genera una variable per a futures connexions
