# Variables per a crear els usuaris al sistema
usuari: usr_prova
password: temporal
clau_usuari_prova: "{{ lookup('file', lookup('env','HOME') + '/.ssh/clau_usuari_prova.pub') }}"
codi_index_html: "{{ lookup('env','HOME') + '/formacio-ansible/codi_html/index1.html' }}"
