# Jordi Casas - 24/06/2025
# Tasques a realitzar per a instal.lar docker en sistemes Ubuntu i Alpine
---
- name: Actualitzar apt cache (si és Debian/Ubuntu)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"

- name: Actualitzar apk cache (si és Alpine)
  ansible.builtin.apk:
    update_cache: yes
  become: yes
  when: ansible_os_family == "Alpine"

- name: Instal·lar paquets necessaris
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Afegir GPG key de Docker (Debian/Ubuntu)
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: yes
  when: ansible_os_family == "Debian"

- name: Afegir repositori de Docker (Debian/Ubuntu)
  ansible.builtin.shell: |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list
  become: yes
  when: ansible_os_family == "Debian"

# Per defecte Alpine té desactivat el repositori community. Cal habilitar-lo per a poder instal.lar els paquets.
- name: Habilitar el repositori community descomentant la línia
  lineinfile:
    dest: /etc/apk/repositories
    regexp: '^#http://elmirror.cl/alpine/v3.21/community'
    line: 'http://elmirror.cl/alpine/v3.21/community'
  when: ansible_os_family == "Alpine"

- name: Actualitzar apt cache (si és Debian/Ubuntu)
  ansible.builtin.apt:
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Actualitzar apk cache (si és Alpine)
  ansible.builtin.apk:
    update_cache: yes
  become: yes
  when: ansible_os_family == "Alpine"

- name: Instal·lar Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Instal·lar Docker en Alpine
  ansible.builtin.apk:
    name: docker
    state: present
  become: yes
  when: ansible_os_family == "Alpine"

- name: Iniciar i habilitar el servei Docker en Alpine
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  become: yes
  when: ansible_os_family == "Alpine"

# Aquesta tasca es comuna als dos sistemes. Cal afegir l'usuari al grup docker
- name: Afegir l'usuari remot al grup docker
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes
